require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe UpdateActionsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # UpdateAction. As you add validations to UpdateAction, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UpdateActionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all update_actions as @update_actions" do
      update_action = UpdateAction.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:update_actions)).to eq([update_action])
    end
  end

  describe "GET #show" do
    it "assigns the requested update_action as @update_action" do
      update_action = UpdateAction.create! valid_attributes
      get :show, {:id => update_action.to_param}, valid_session
      expect(assigns(:update_action)).to eq(update_action)
    end
  end

  describe "GET #new" do
    it "assigns a new update_action as @update_action" do
      get :new, {}, valid_session
      expect(assigns(:update_action)).to be_a_new(UpdateAction)
    end
  end

  describe "GET #edit" do
    it "assigns the requested update_action as @update_action" do
      update_action = UpdateAction.create! valid_attributes
      get :edit, {:id => update_action.to_param}, valid_session
      expect(assigns(:update_action)).to eq(update_action)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new UpdateAction" do
        expect {
          post :create, {:update_action => valid_attributes}, valid_session
        }.to change(UpdateAction, :count).by(1)
      end

      it "assigns a newly created update_action as @update_action" do
        post :create, {:update_action => valid_attributes}, valid_session
        expect(assigns(:update_action)).to be_a(UpdateAction)
        expect(assigns(:update_action)).to be_persisted
      end

      it "redirects to the created update_action" do
        post :create, {:update_action => valid_attributes}, valid_session
        expect(response).to redirect_to(UpdateAction.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved update_action as @update_action" do
        post :create, {:update_action => invalid_attributes}, valid_session
        expect(assigns(:update_action)).to be_a_new(UpdateAction)
      end

      it "re-renders the 'new' template" do
        post :create, {:update_action => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested update_action" do
        update_action = UpdateAction.create! valid_attributes
        put :update, {:id => update_action.to_param, :update_action => new_attributes}, valid_session
        update_action.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested update_action as @update_action" do
        update_action = UpdateAction.create! valid_attributes
        put :update, {:id => update_action.to_param, :update_action => valid_attributes}, valid_session
        expect(assigns(:update_action)).to eq(update_action)
      end

      it "redirects to the update_action" do
        update_action = UpdateAction.create! valid_attributes
        put :update, {:id => update_action.to_param, :update_action => valid_attributes}, valid_session
        expect(response).to redirect_to(update_action)
      end
    end

    context "with invalid params" do
      it "assigns the update_action as @update_action" do
        update_action = UpdateAction.create! valid_attributes
        put :update, {:id => update_action.to_param, :update_action => invalid_attributes}, valid_session
        expect(assigns(:update_action)).to eq(update_action)
      end

      it "re-renders the 'edit' template" do
        update_action = UpdateAction.create! valid_attributes
        put :update, {:id => update_action.to_param, :update_action => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested update_action" do
      update_action = UpdateAction.create! valid_attributes
      expect {
        delete :destroy, {:id => update_action.to_param}, valid_session
      }.to change(UpdateAction, :count).by(-1)
    end

    it "redirects to the update_actions list" do
      update_action = UpdateAction.create! valid_attributes
      delete :destroy, {:id => update_action.to_param}, valid_session
      expect(response).to redirect_to(update_actions_url)
    end
  end

end
